"use client";
import Link from '@mui/material';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {CssBaseline, ThemeProvider} from "@mui/material";
import { createTheme } from '@mui/material/styles';
import { useMemo } from 'react';
import {themeSettings} from "./theme";
import {BrowserRouter, Route, Routes} from "react-router-dom";
import {Box} from "@mui/material";
import Navbar from "./scenes/navbar/index.js";
import Dashboard from "./scenes/dashboard/index.tsx"
import Chatbot from "./scenes/chatbot/index.tsx"

export default function Home() {
  const theme = useMemo(() => createTheme(themeSettings), [])
  return (
    <div className={styles.container}>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ThemeProvider theme={theme}>
      <CssBaseline/>
      <div className={styles.container}>
        <Navbar/>
        <Dashboard/>
     
      </div>
    </ThemeProvider>
  </div>
  );
}
